name: Terraform Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform_validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: ./test.sh
